org: luzzif
app: swapr-coingecko-farming
service: swapr-coingecko-farming
provider:
  name: aws
  runtime: nodejs12.x
plugins:
  - serverless-plugin-typescript
  - serverless-offline
functions:
  pools:
    handler: app/pools/handler.pools
    events:
      - http:
          path: pools
          method: get
  circulating-supply:
    handler: app/circulating-supply/handler.circulatingSupply
    environment: ${file(.env.json)}
    events:
      - http:
          path: circulating-supply
          method: get
