org: luzzif
app: swapr-coingecko
service: swapr-coingecko
useDotenv: true
provider:
  name: aws
  runtime: nodejs12.x
plugins:
  - serverless-plugin-typescript
  - serverless-offline
functions:
  pools:
    handler: app/pools/handler.pools
    events:
      - http:
          path: pools
          method: get
  circulating-supply:
    handler: app/circulating-supply/handler.circulatingSupply
    events:
      - http:
          path: circulating-supply
          method: get
