org: luzzif
app: swapr-coingecko-farming
service: swapr-coingecko-farming
provider:
  name: aws
  runtime: nodejs16.x
  timeout: 20
package:
  patterns:
    - '!node_modules/**'
plugins:
  - serverless-webpack
  - serverless-offline
functions:
  pools:
    handler: app/pools/handler.pools
    events:
      - http:
          path: pools
          method: get
  circulating-supply:
    handler: app/circulating-supply/handler.circulatingSupply
    events:
      - http:
          path: circulating-supply
          method: get
  uncollected-protocol-fees:
    handler: app/uncollected-protocol-fees/handler.uncollectedProtocolFees
    events:
      - http:
          path: uncollected-protocol-fees
          method: get
          cors: true
